/**
 * Executor Agent Durable Object
 *
 * Executes plans generated by Planner Agents:
 * - Executes individual steps
 * - Handles errors with retry logic
 * - Tracks progress
 * - Returns final result
 */

import type {
  Plan,
  PlanResult,
  StepResult,
  RecoveryAction,
  Context,
  ProgressUpdate,
} from '../lib/agents/types';

export interface Env {
  EXECUTOR_DO: DurableObjectNamespace;
  DIRECTOR_DO: DurableObjectNamespace;
  AGENTS_KV?: KVNamespace;
}

/**
 * Executor Agent State
 */
interface ExecutorState {
  activePlan: Plan | null;
  currentStep: number;
  results: StepResult[];
  status: 'idle' | 'executing' | 'completed' | 'failed';
  startTime: number;
  errorCount: number;
}

/**
 * Executor Agent - Executes plans from Planner Agents
 *
 * Features:
 * - Step-by-step execution
 * - Error handling with recovery
 * - Progress tracking
 * - Retry logic
 * - State persistence
 */
export class ExecutorAgent implements DurableObject {
  private state: DurableObjectState;
  private _env: Env;
  private storage: DurableObjectStorage;
  private executorState: ExecutorState;

  constructor(state: DurableObjectState, env: Env) {
    this.state = state;
    this._env = env;
    this.storage = state.storage;

    // Initialize state
    this.executorState = {
      activePlan: null,
      currentStep: 0,
      results: [],
      status: 'idle',
      startTime: 0,
      errorCount: 0,
    };

    // Load from storage
    this.initializeFromStorage();
  }

  /**
   * Fetch handler for incoming requests
   */
  async fetch(request: Request): Promise<Response> {
    const url = new URL(request.url);
    const path = url.pathname;
    const method = request.method;

    try {
      if (method === 'POST' && path === '/execute') {
        return this.handleExecute(request);
      }

      if (method === 'GET' && path === '/progress') {
        return this.handleGetProgress();
      }

      if (method === 'GET' && path === '/state') {
        return this.handleGetState();
      }

      if (method === 'POST' && path === '/reset') {
        return this.handleReset();
      }

      return new Response('Not found', { status: 404 });
    } catch (error) {
      return new Response(
        JSON.stringify({
          error: error instanceof Error ? error.message : 'Unknown error',
          stack: error instanceof Error ? error.stack : undefined,
        }),
        { status: 500, headers: { 'Content-Type': 'application/json' } }
      );
    }
  }

  /**
   * Handle execute request
   */
  private async handleExecute(request: Request): Promise<Response> {
    const body = (await request.json()) as {
      plan: Plan;
      context: Context;
    };

    // Execute plan
    const result = await this.execute(body.plan, body.context);

    return new Response(
      JSON.stringify(result),
      { status: 200, headers: { 'Content-Type': 'application/json' } }
    );
  }

  /**
   * Handle get progress request
   */
  private async handleGetProgress(): Promise<Response> {
    if (!this.executorState.activePlan) {
      return new Response(
        JSON.stringify({ error: 'No active plan' }),
        { status: 404, headers: { 'Content-Type': 'application/json' } }
      );
    }

    const progress: ProgressUpdate = {
      planId: this.executorState.activePlan.id,
      stepNumber: this.executorState.currentStep,
      totalSteps: this.executorState.activePlan.steps.length,
      currentStep: this.executorState.activePlan.steps[this.executorState.currentStep]?.description || 'Completed',
      percentage: (this.executorState.currentStep / this.executorState.activePlan.steps.length) * 100,
      estimatedTimeRemaining: this.calculateEstimatedTimeRemaining(),
    };

    return new Response(
      JSON.stringify(progress),
      { status: 200, headers: { 'Content-Type': 'application/json' } }
    );
  }

  /**
   * Handle get state request
   */
  private async handleGetState(): Promise<Response> {
    return new Response(
      JSON.stringify({
        ...this.executorState,
        activePlan: this.executorState.activePlan,
      }),
      { status: 200, headers: { 'Content-Type': 'application/json' } }
    );
  }

  /**
   * Handle reset request
   */
  private async handleReset(): Promise<Response> {
    this.executorState = {
      activePlan: null,
      currentStep: 0,
      results: [],
      status: 'idle',
      startTime: 0,
      errorCount: 0,
    };

    await this.persistState();

    return new Response(
      JSON.stringify({ success: true }),
      { status: 200, headers: { 'Content-Type': 'application/json' } }
    );
  }

  /**
   * Main execution logic
   */
  async execute(plan: Plan, context: Context): Promise<PlanResult> {
    const startTime = Date.now();

    // Initialize execution state
    this.executorState.activePlan = plan;
    this.executorState.currentStep = 0;
    this.executorState.results = [];
    this.executorState.status = 'executing';
    this.executorState.startTime = startTime;

    await this.persistState();

    try {
      // Execute each step
      for (let i = 0; i < plan.steps.length; i++) {
        const step = plan.steps[i];
        if (!step) continue;

        // Check dependencies
        if (!this.areDependenciesMet(step, this.executorState.results)) {
          throw new Error(`Dependencies not met for step ${step.id}`);
        }

        // Update current step
        this.executorState.currentStep = i;
        await this.persistState();

        // Execute step
        const stepResult = await this.executeStep(step, context);

        // Store result
        this.executorState.results.push(stepResult);
        await this.persistState();

        // Handle errors
        if (stepResult.status === 'failed') {
          const recovery = await this.handleErrors(stepResult.error || 'Unknown error', step);

          if (recovery.type === 'retry') {
            // Retry step
            i--; // Retry current step
            continue;
          } else if (recovery.type === 'skip') {
            // Skip step and continue
            continue;
          } else if (recovery.type === 'abort') {
            // Abort execution
            throw new Error('Execution aborted: Retry limit exceeded');
          } else if (recovery.type === 'fallback') {
            // Use fallback executor
            const fallbackResult = await this.executeWithFallback(
              step,
              context,
              recovery.fallbackTo?.agentId || ''
            );
            this.executorState.results.push(fallbackResult);
            await this.persistState();
          }
        }

        // Update progress
        await this.updateProgress(i + 1);
      }

      // Mark as completed
      this.executorState.status = 'completed';

      // Aggregate results
      const output = this.aggregateResults(this.executorState.results);

      const endTime = Date.now();

      const result: PlanResult = {
        planId: plan.id,
        executorId: this.state.id.toString(),
        status: 'completed',
        steps: this.executorState.results,
        output,
        metrics: {
          totalTokens: this.executorState.results.reduce((sum, r) => sum + r.tokens, 0),
          latency: endTime - startTime,
          startTime,
          endTime,
        },
      };

      await this.persistState();

      return result;
    } catch (error) {
      this.executorState.status = 'failed';
      this.executorState.errorCount++;
      await this.persistState();

      return {
        planId: plan.id,
        executorId: this.state.id.toString(),
        status: 'failed',
        steps: this.executorState.results,
        output: '',
        error: error instanceof Error ? error.message : 'Unknown error',
        metrics: {
          totalTokens: this.executorState.results.reduce((sum, r) => sum + r.tokens, 0),
          latency: Date.now() - startTime,
          startTime,
          endTime: Date.now(),
        },
      };
    }
  }

  /**
   * Execute a single step
   */
  private async executeStep(step: { id: string; type: string; description: string; input: Record<string, unknown> }, context: Context): Promise<StepResult> {
    const startTime = performance.now();

    try {
      let output = '';
      let tokens = 0;

      switch (step.type) {
        case 'analyze':
          output = await this.performAnalysis(step, context);
          tokens = Math.floor(step.input['estimatedTokens'] as number || 500);
          break;

        case 'generate':
          output = await this.performGeneration(step, context);
          tokens = Math.floor(step.input['estimatedTokens'] as number || 1000);
          break;

        case 'validate':
          output = await this.performValidation(step, context);
          tokens = Math.floor(step.input['estimatedTokens'] as number || 300);
          break;

        case 'retrieve':
          output = await this.performRetrieval(step, context);
          tokens = Math.floor(step.input['estimatedTokens'] as number || 200);
          break;

        default:
          throw new Error(`Unknown step type: ${step.type}`);
      }

      const latency = performance.now() - startTime;

      return {
        stepId: step.id,
        status: 'completed',
        output,
        tokens,
        latency,
        retries: 0,
      };
    } catch (error) {
      const latency = performance.now() - startTime;

      return {
        stepId: step.id,
        status: 'failed',
        error: error instanceof Error ? error.message : 'Unknown error',
        tokens: 0,
        latency,
        retries: 0,
      };
    }
  }

  /**
   * Perform analysis step
   */
  private async performAnalysis(
    step: { id: string; input: Record<string, unknown> },
    _context: Context
  ): Promise<string> {
    // Simulate analysis logic
    // In production, this would call an LLM or other service
    const message = step.input['message'] as string || '';

    return `[Analysis] Analyzed: ${message.substring(0, 100)}...`;
  }

  /**
   * Perform generation step
   */
  private async performGeneration(
    step: { id: string; input: Record<string, unknown> },
    _context: Context
  ): Promise<string> {
    // Simulate generation logic
    // In production, this would call an LLM API
    const message = step.input['message'] as string || '';

    return `[Generated] Based on: ${message.substring(0, 100)}...\n\n// Generated content would appear here`;
  }

  /**
   * Perform validation step
   */
  private async performValidation(
    _step: { id: string; input: Record<string, unknown> },
    _context: Context
  ): Promise<string> {
    // Simulate validation logic
    return '[Validation] Content validated successfully';
  }

  /**
   * Perform retrieval step
   */
  private async performRetrieval(
    _step: { id: string; input: Record<string, unknown> },
    _context: Context
  ): Promise<string> {
    // Simulate retrieval logic
    // In production, this would query KV, R2, or vector DB
    return '[Retrieved] Relevant context and information';
  }

  /**
   * Handle errors with recovery strategy
   */
  private async handleErrors(_error: string, _step: { id: string }): Promise<RecoveryAction> {
    this.executorState.errorCount++;

    // Determine recovery strategy based on error count
    if (this.executorState.errorCount < 3) {
      // Retry with exponential backoff
      return {
        type: 'retry',
        retryWith: {
          backoffMs: Math.pow(2, this.executorState.errorCount) * 1000,
        },
      };
    } else if (this.executorState.errorCount < 5) {
      // Try fallback
      return {
        type: 'fallback',
        fallbackTo: {
          agentId: `fallback-executor-${this.state.id.toString()}`,
          reason: 'Primary executor failed repeatedly',
        },
      };
    } else {
      // Abort
      return {
        type: 'abort',
      };
    }
  }

  /**
   * Execute step with fallback executor
   */
  private async executeWithFallback(
    step: { id: string; type: string; description: string; input: Record<string, unknown> },
    _context: Context,
    fallbackAgentId: string
  ): Promise<StepResult> {
    // In production, this would call a different executor DO
    // For now, we'll simulate a successful execution
    return {
      stepId: step.id,
      status: 'completed',
      output: `[Fallback] Executed via ${fallbackAgentId}`,
      tokens: Math.floor(step.input['estimatedTokens'] as number || 500),
      latency: 500,
      retries: 0,
    };
  }

  /**
   * Check if step dependencies are met
   */
  private areDependenciesMet(step: { dependencies: string[] }, results: StepResult[]): boolean {
    for (const depId of step.dependencies) {
      const depResult = results.find(r => r.stepId === depId);
      if (!depResult || depResult.status !== 'completed') {
        return false;
      }
    }
    return true;
  }

  /**
   * Update progress
   */
  private async updateProgress(_step: number): Promise<void> {
    // In production, this could send notifications or update a progress store
    // For now, we just persist state
    await this.persistState();
  }

  /**
   * Aggregate results into final output
   */
  private aggregateResults(results: StepResult[]): string {
    return results
      .filter(r => r.status === 'completed' && r.output)
      .map(r => r.output)
      .join('\n\n');
  }

  /**
   * Calculate estimated time remaining
   */
  private calculateEstimatedTimeRemaining(): number {
    if (!this.executorState.activePlan || this.executorState.currentStep === 0) {
      return 0;
    }

    const stepsCompleted = this.executorState.currentStep;
    const stepsRemaining = this.executorState.activePlan.steps.length - stepsCompleted;
    const avgTimePerStep = (Date.now() - this.executorState.startTime) / stepsCompleted;

    return Math.floor(avgTimePerStep * stepsRemaining);
  }

  /**
   * Initialize state from storage
   */
  private async initializeFromStorage(): Promise<void> {
    try {
      const stored = await this.storage.get<ExecutorState>('executorState');

      if (stored) {
        this.executorState = stored;
      }
    } catch (error) {
      console.error('Failed to load state from storage:', error);
    }
  }

  /**
   * Persist state to storage
   */
  private async persistState(): Promise<void> {
    try {
      await this.storage.put('executorState', this.executorState);
    } catch (error) {
      console.error('Failed to persist state:', error);
    }
  }

  /**
   * Alarm handler for periodic maintenance
   */
  async alarm(): Promise<void> {
    // Reset state if stuck in executing state for too long (> 10 minutes)
    if (
      this.executorState.status === 'executing' &&
      Date.now() - this.executorState.startTime > 10 * 60 * 1000
    ) {
      this.executorState.status = 'failed';
      this.executorState.errorCount++;
      await this.persistState();
    }
  }
}

/**
 * Helper function to create Executor Agent stub
 */
export function createExecutorStub(env: Env, planId: string): DurableObjectStub {
  return env.EXECUTOR_DO.get(env.EXECUTOR_DO.idFromName(`executor-${planId}`));
}
