/**
 * Hybrid IDE Test Page
 *
 * This is a demonstration page that showcases all the components
 * of the Cocapn Hybrid IDE interface working together.
 */

import { html } from 'hono/html';
import { HybridIDE } from '../components/hybrid-ide';

export default async function HybridIDETestPage() {
  const config = {
    sessionId: 'test-session-' + Date.now(),
    project: {
      name: 'Cocapn Demo Project',
      files: {
        'src/index.ts': {
          name: 'index.ts',
          content: `// Welcome to Cocapn - Cloudflare Workers IDE
import { Hono } from 'hono';

const app = new Hono();

// AI-powered endpoint
app.get('/ai/:query', (c) => {
  const query = c.req.param('query');
  return c.json({
    query,
    response: "This would be generated by AI assistance",
    timestamp: new Date().toISOString()
  });
});

// Database integration example
app.get('/db/users', (c) => {
  return c.json([
    { id: 1, name: "Alice", email: "alice@example.com" },
    { id: 2, name: "Bob", email: "bob@example.com" }
  ]);
});

export default app;`,
        modified: Date.now()
      }
    },
    providers: [
      {
        id: 'manus',
        name: 'Manus',
        description: 'Primary AI provider for code generation',
        icon: '🤖',
        recommended: true,
        features: ['Code generation', 'Asset creation', 'Fast responses']
      },
      {
        id: 'zai',
        name: 'Z.ai',
        description: 'Image generation and visual assets',
        icon: '🎨',
        recommended: false,
        features: ['Image generation', 'Low cost', 'Scalable']
      },
      {
        id: 'minimax',
        name: 'Minimax.ai',
        description: 'Backup image provider',
        icon: '🖼️',
        recommended: false,
        features: ['Image generation', 'Backup', 'Reliable']
      },
      {
        id: 'claude',
        name: 'Claude',
        description: 'Advanced reasoning and complex tasks',
        icon: '🧠',
        recommended: false,
        features: ['Advanced reasoning', 'Large context', 'Helpful']
      },
      {
        id: 'grok',
        name: 'Grok (xAI)',
        description: 'Conversational AI integration',
        icon: '🗣️',
        recommended: false,
        features: ['Conversational', 'Fast responses', 'Context-aware']
      }
    ]
  };

  const ideHtml = HybridIDE.render(config);

  return html`
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Cocapn Hybrid IDE - Test Interface</title>
      <style>
        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }

        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          background: #0f172a;
          color: #e2e8f0;
          overflow: hidden;
        }

        /* Loading Screen */
        .loading-screen {
          position: fixed;
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
          background: #0f172a;
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          z-index: 9999;
        }

        .loading-content {
            text-align: center;
        }

        .loading-logo {
          font-size: 48px;
          margin-bottom: 20px;
          animation: pulse 2s infinite;
        }

        .loading-text {
          font-size: 18px;
          color: #94a3b8;
          margin-bottom: 8px;
        }

        .loading-subtext {
          font-size: 14px;
          color: #64748b;
          margin-bottom: 30px;
        }

        .loading-progress {
          width: 300px;
          height: 4px;
          background: #1e293b;
          border-radius: 2px;
          overflow: hidden;
          margin-bottom: 20px;
        }

        .loading-bar {
          height: 100%;
          background: linear-gradient(90deg, #3b82f6, #8b5cf6);
          width: 0%;
          transition: width 0.3s ease;
        }

        @keyframes pulse {
          0%, 100% { opacity: 1; transform: scale(1); }
          50% { opacity: 0.8; transform: scale(1.05); }
        }

        /* Page Container */
        .page-container {
          height: 100vh;
          display: flex;
          flex-direction: column;
          background: #0f172a;
        }

        /* Header */
        .test-header {
          background: #1e293b;
          border-bottom: 1px solid #334155;
          padding: 16px 24px;
          display: flex;
          align-items: center;
          justify-content: space-between;
          flex-shrink: 0;
        }

        .header-left {
          display: flex;
          align-items: center;
          gap: 16px;
        }

        .logo {
          display: flex;
          align-items: center;
          gap: 8px;
          font-size: 20px;
          font-weight: 600;
          color: #3b82f6;
        }

        .test-title {
          font-size: 18px;
          color: #e2e8f0;
        }

        .header-right {
          display: flex;
          align-items: center;
          gap: 12px;
        }

        .test-info {
          font-size: 12px;
          color: #94a3b8;
          background: #1e293b;
          padding: 4px 8px;
          border-radius: 4px;
        }

        /* Content Area */
        .content-area {
          flex: 1;
          overflow: hidden;
          position: relative;
        }

        /* Test Controls */
        .test-controls {
          position: absolute;
          top: 16px;
          right: 16px;
          z-index: 100;
          display: flex;
          gap: 8px;
        }

        .test-btn {
          background: #1e293b;
          border: 1px solid #334155;
          color: #e2e8f0;
          padding: 8px 12px;
          border-radius: 6px;
          cursor: pointer;
          font-size: 12px;
          transition: all 0.2s;
        }

        .test-btn:hover {
          background: #334155;
          border-color: #475569;
        }

        .test-btn.primary {
          background: #3b82f6;
          border-color: #3b82f6;
        }

        .test-btn.primary:hover {
          background: #2563eb;
        }

        /* Test Instructions */
        .test-instructions {
          position: absolute;
          bottom: 16px;
          left: 16px;
          right: 16px;
          background: #1e293b;
          border: 1px solid #334155;
          border-radius: 8px;
          padding: 12px;
          font-size: 12px;
          color: #94a3b8;
          z-index: 100;
        }

        .test-instructions h4 {
          color: #e2e8f0;
          margin-bottom: 4px;
        }

        .test-instructions ul {
          list-style: none;
          padding-left: 0;
        }

        .test-instructions li {
          margin-bottom: 2px;
        }

        .test-instructions li::before {
          content: "▸ ";
          color: #3b82f6;
        }

        /* Error Console */
        .error-console {
          position: absolute;
          top: 50%;
          left: 50%;
          transform: translate(-50%, -50%);
          background: #dc2626;
          border: 1px solid #ef4444;
          border-radius: 8px;
          padding: 20px;
          max-width: 500px;
          z-index: 200;
          display: none;
        }

        .error-console.show {
          display: block;
        }

        .error-console h4 {
          color: white;
          margin-bottom: 8px;
        }

        .error-console p {
          color: #fecaca;
          font-size: 12px;
        }

        .error-console button {
          background: white;
          color: #dc2626;
          border: none;
          padding: 4px 8px;
          border-radius: 4px;
          cursor: pointer;
          margin-top: 8px;
          font-size: 11px;
        }

        /* Responsive Design */
        @media (max-width: 768px) {
          .test-header {
            flex-wrap: wrap;
            padding: 12px 16px;
          }

          .test-controls {
            flex-wrap: wrap;
          }

          .test-instructions {
            font-size: 11px;
            padding: 8px;
          }
        }

        @media (max-width: 480px) {
          .test-instructions {
            display: none;
          }

          .test-controls {
            position: relative;
            top: auto;
            right: auto;
            margin-bottom: 8px;
          }
        }
      </style>
    </head>
    <body>
      <!-- Loading Screen -->
      <div id="loading-screen" class="loading-screen">
        <div class="loading-content">
          <div class="loading-logo">🚀</div>
          <div class="loading-text">Initializing Cocapn Hybrid IDE</div>
          <div class="loading-subtext">Loading all components...</div>
          <div class="loading-progress">
            <div id="loading-bar" class="loading-bar"></div>
          </div>
          <div id="loading-status" class="loading-text">Preparing environment</div>
        </div>
      </div>

      <!-- Page Content -->
      <div class="page-container">
        <!-- Test Header -->
        <header class="test-header">
          <div class="header-left">
            <div class="logo">
              <span>🚀</span>
              <span>Cocapn</span>
            </div>
            <div class="test-title">Hybrid IDE - Test Interface</div>
          </div>
          <div class="header-right">
            <div class="test-info">v1.0.0</div>
            <div class="test-info">${config.sessionId.slice(-8)}</div>
          </div>
        </header>

        <!-- Content Area -->
        <div class="content-area">
          <!-- Test Controls -->
          <div class="test-controls">
            <button class="test-btn" onclick="runTestSuite()">🧪 Test All</button>
            <button class="test-btn" onclick="testChatInterface()">💬 Chat</button>
            <button class="test-btn" onclick="testEditor()">📝 Editor</button>
            <button class="test-btn" onclick="testFileTree()">📁 Files</button>
            <button class="test-btn" onclick="testPreview()">🌐 Preview</button>
            <button class="test-btn" onclick="testTerminal()">💻 Terminal</button>
            <button class="test-btn primary" onclick="loadIDE()">🚀 Load IDE</button>
          </div>

          <!-- Test Instructions -->
          <div class="test-instructions">
            <h4>Test Instructions:</h4>
            <ul>
              <li>Click "Load IDE" to initialize the complete Hybrid IDE interface</li>
              <li>Test individual components using the test buttons above</li>
              <li>Verify all features work: provider switching, file operations, deployment</li>
              <li>Check responsive design on mobile devices</li>
              <li>Test keyboard shortcuts (Ctrl+E for editor, Ctrl+T for terminal, etc.)</li>
            </ul>
          </div>

          <!-- Error Console -->
          <div id="error-console" class="error-console">
            <h4>⚠️ Error Detected</h4>
            <p id="error-message">An error occurred while loading the interface.</p>
            <button onclick="hideErrorConsole()">Dismiss</button>
          </div>
        </div>
      </div>

      <!-- IDE Interface -->
      <div id="ide-container" style="display: none;">
        ${ideHtml}
      </div>

      <script>
        // Global state
        let loadProgress = 0;
        let testResults = [];
        const components = ['Chat', 'Editor', 'FileTree', 'Preview', 'Terminal'];

        // Loading system
        function startLoading() {
          const loadingScreen = document.getElementById('loading-screen');
          const loadingBar = document.getElementById('loading-bar');
          const loadingStatus = document.getElementById('loading-status');

          const loadingSteps = [
            'Initializing environment',
            'Loading Chat Interface',
            'Loading Editor Panel',
            'Loading File Tree',
            'Loading Preview Panel',
            'Loading Terminal Panel',
            'Setting up keyboard shortcuts',
            'Ready to launch'
          ];

          let currentStep = 0;

          const updateProgress = () => {
            if (currentStep < loadingSteps.length) {
              loadProgress = ((currentStep + 1) / loadingSteps.length) * 100;
              loadingBar.style.width = loadProgress + '%';
              loadingStatus.textContent = loadingSteps[currentStep];
              currentStep++;

              setTimeout(updateProgress, 500);
            } else {
              setTimeout(() => {
                loadingScreen.style.display = 'none';
              }, 1000);
            }
          };

          updateProgress();
        }

        // Error handling
        function showError(message) {
          const errorConsole = document.getElementById('error-console');
          const errorMessage = document.getElementById('error-message');
          errorMessage.textContent = message;
          errorConsole.classList.add('show');

          // Log error
          console.error('Cocapn IDE Test Error:', message);
          testResults.push({ component: 'Global', status: 'error', message });
        }

        function hideErrorConsole() {
          document.getElementById('error-console').classList.remove('show');
        }

        // Component testing functions
        function testChatInterface() {
          console.log('Testing Chat Interface...');
          try {
            // Simulate chat functionality
            const chatInput = document.querySelector('#chat-input');
            if (chatInput) {
              chatInput.value = 'Hello, this is a test message!';
              chatInput.focus();
              testResults.push({ component: 'Chat', status: 'success' });
            } else {
              throw new Error('Chat input not found');
            }
          } catch (error) {
            showError('Chat Interface Test Failed: ' + error.message);
          }
        }

        function testEditor() {
          console.log('Testing Editor Interface...');
          try {
            // Test editor toggle
            const editorPanel = document.querySelector('.editor-panel');
            if (editorPanel) {
              editorPanel.classList.add('active');
              testResults.push({ component: 'Editor', status: 'success' });
            } else {
              throw new Error('Editor panel not found');
            }
          } catch (error) {
            showError('Editor Interface Test Failed: ' + error.message);
          }
        }

        function testFileTree() {
          console.log('Testing File Tree...');
          try {
            const fileTree = document.querySelector('.filetree-panel');
            if (fileTree) {
              fileTree.classList.add('active');
              testResults.push({ component: 'FileTree', status: 'success' });
            } else {
              throw new Error('File tree panel not found');
            }
          } catch (error) {
            showError('File Tree Test Failed: ' + error.message);
          }
        }

        function testPreview() {
          console.log('Testing Preview Panel...');
          try {
            const previewPanel = document.querySelector('.preview-panel');
            if (previewPanel) {
              previewPanel.classList.add('active');
              testResults.push({ component: 'Preview', status: 'success' });
            } else {
              throw new Error('Preview panel not found');
            }
          } catch (error) {
            showError('Preview Panel Test Failed: ' + error.message);
          }
        }

        function testTerminal() {
          console.log('Testing Terminal Panel...');
          try {
            const terminalPanel = document.querySelector('.terminal-panel');
            if (terminalPanel) {
              terminalPanel.classList.add('active');
              const terminalInput = document.querySelector('#terminal-input');
              if (terminalInput) {
                terminalInput.value = 'wrangler dev --local';
                terminalInput.focus();
                testResults.push({ component: 'Terminal', status: 'success' });
              } else {
                throw new Error('Terminal input not found');
              }
            } else {
              throw new Error('Terminal panel not found');
            }
          } catch (error) {
            showError('Terminal Test Failed: ' + error.message);
          }
        }

        // Complete test suite
        function runTestSuite() {
          console.log('🧪 Running Complete Test Suite...');
          testResults = [];

          // Test each component
          components.forEach(component => {
            try {
              window['test' + component]();
            } catch (error) {
              testResults.push({ component, status: 'error', message: error.message });
              showError(`${component} Test Failed: ${error.message}`);
            }
          });

          // Show results
          const successCount = testResults.filter(r => r.status === 'success').length;
          const totalCount = testResults.length;

          if (successCount === totalCount) {
            alert(`All tests passed! (${successCount}/${totalCount} components working)`);
          } else {
            const failures = totalCount - successCount;
            alert(`Warning: ${failures} tests failed out of ${totalCount}. Check console for details.`);
          }

          console.log('Test Results:', testResults);
        }

        // Load the complete IDE
        function loadIDE() {
          console.log('🚀 Loading Complete Hybrid IDE...');
          try {
            // Hide test interface
            document.querySelector('.page-container').style.display = 'none';

            // Show IDE
            document.getElementById('ide-container').style.display = 'block';

            // Initialize IDE state
            if (window.HybridIDE) {
              console.log('✅ Hybrid IDE initialized successfully');

              // Set a message in the chat interface
              setTimeout(() => {
                const chatInput = document.querySelector('#chat-input');
                if (chatInput) {
                  chatInput.value = 'Welcome to Cocapn Hybrid IDE! Try asking me to create a new Cloudflare Worker project.';
                  chatInput.focus();
                }
              }, 1000);
            } else {
              throw new Error('Hybrid IDE component not found');
            }
          } catch (error) {
            showError('Failed to load IDE: ' + error.message);
          }
        }

        // Initialize on page load
        document.addEventListener('DOMContentLoaded', () => {
          console.log('🔬 Cocapn Hybrid IDE Test Interface Loaded');

          // Start loading animation
          setTimeout(() => {
            startLoading();
          }, 500);

          // Set up keyboard shortcuts for testing
          document.addEventListener('keydown', (event) => {
            // Ctrl+Shift+T: Run test suite
            if ((event.ctrlKey || event.metaKey) && event.shiftKey && event.key.toLowerCase() === 't') {
              event.preventDefault();
              runTestSuite();
            }

            // Ctrl+Shift+L: Load IDE
            if ((event.ctrlKey || event.metaKey) && event.shiftKey && event.key.toLowerCase() === 'l') {
              event.preventDefault();
              loadIDE();
            }
          });

          console.log('💡 Keyboard shortcuts: Ctrl+Shift+T (test), Ctrl+Shift+L (load IDE)');
        });

        // Error handling for unhandled errors
        window.addEventListener('error', (event) => {
          showError('JavaScript Error: ' + event.error.message);
          event.preventDefault();
        });

        // Performance monitoring
        let performanceData = {
          loadStart: performance.now(),
          componentLoadTimes: {}
        };

        // Track component load times
        components.forEach(component => {
          const startTime = performance.now();

          // Simulate component load
          setTimeout(() => {
            const loadTime = performance.now() - startTime;
            performanceData.componentLoadTimes[component] = loadTime;
            console.log(`${component} component loaded in ${loadTime.toFixed(2)}ms`);
          }, Math.random() * 1000 + 500);
        });
      </script>
    </body>
    </html>
  `;
}