/**
 * Hybrid IDE Main Interface
 *
 * Features:
 * - Chat-first development interface
 * - Monaco editor panels
 * - File tree with locking
 * - Live Worker preview
 * - Terminal for Wrangler
 * - Ad banners for monetization
 * - Responsive design
 */

import { html } from 'hono/html';
import { ChatInterface } from './chat-interface';
import { EditorPanel } from './editor-panel';
import { FileTree } from './file-tree';
import { PreviewPanel } from './preview-panel';
import { TerminalPanel } from './terminal-panel';

export interface HybridIDEConfig {
  sessionId: string;
  project?: {
    name: string;
    files: any[];
  };
  providers: Array<{
    id: 'manus' | 'zai' | 'minimax' | 'claude' | 'grok';
    name: string;
    description: string;
    icon: string;
    recommended: boolean;
  }>;
}

export interface HybridIDEState {
  sidebarOpen: boolean;
  editorOpen: boolean;
  terminalOpen: boolean;
  activePanel: 'chat' | 'editor' | 'filetree' | 'preview' | 'terminal';
  currentProvider: 'manus' | 'zai' | 'minimax' | 'claude' | 'grok';
}

export const HybridIDE = {
  // Default state
  defaultState: {
    sidebarOpen: true,
    editorOpen: false,
    terminalOpen: false,
    activePanel: 'chat',
    currentProvider: 'manus',
  } as HybridIDEState,

  // Sample file structure
  defaultFiles: {
    'src/index.ts': {
      name: 'index.ts',
      content: `
// Welcome to Cocapn - Hybrid IDE
// This is a Cloudflare Worker starter template

import { Hono } from 'hono';

const app = new Hono();

app.get('/', (c) => {
  return c.json({
    message: 'Welcome to Cocapn!',
    timestamp: new Date().toISOString(),
    provider: 'manus',
    features: ['chat-based development', 'monaco editor', 'live preview', 'terminal integration']
  });
});

app.get('/hello/:name', (c) => {
  const name = c.req.param('name');
  return c.json({
    message: \`Hello, \${name}!\`
  });
});

export default app;
`.trim()
    },
    'src/handlers.ts': {
      name: 'handlers.ts',
      content: `
// Custom request handlers
// Generated by Cocapn

export async function handleExampleRequest(c) {
  return c.json({
    status: 'success',
    data: {
      requestId: crypto.randomUUID(),
      processed: true
    }
  });
}
`.trim()
    },
    'wrangler.toml': {
      name: 'wrangler.toml',
      content: `
# Wrangler configuration
# Generated by Cocapn

name = "cocapn-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
vars = { ENV = "production" }

[env.staging]
vars = { ENV = "staging" }
`.trim()
    },
    'package.json': {
      name: 'package.json',
      content: `{
  "name": "cocapn-worker",
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "dev": "wrangler dev --local",
    "deploy": "wrangler deploy",
    "tail": "wrangler tail"
  },
  "dependencies": {
    "hono": "^3.0.0"
  },
  "devDependencies": {
    "wrangler": "^3.0.0"
  }
}`
    }
  } as any,

  render: (config: HybridIDEConfig) => {
    const initialState = HybridIDE.defaultState;

    return html`
      <div class="hybrid-ide-container">
        <!-- Header -->
        <header class="ide-header">
          <div class="header-left">
            <button class="menu-toggle" onclick="toggleSidebar()">
              ☰
            </button>
            <div class="project-info">
              <h1 class="project-name">${escapeHtml(config.project?.name || 'New Project')}</h1>
              <div class="project-status">
                <span class="status-ready">✓ Ready</span>
                <span class="files-count">${Object.keys(HybridIDE.defaultFiles).length} files</span>
              </div>
            </div>
          </div>

          <div class="header-center">
            <div class="provider-tabs">
              ${config.providers.map(provider => `
                <button class="provider-tab ${initialState.currentProvider === provider.id ? 'active' : ''}"
                        onclick="switchProvider('${escapeHtml(provider.id)}')"
                        title="${escapeHtml(provider.description)}">
                  ${provider.icon} ${provider.recommended ? '★' : ''}
                </button>
              `).join('')}
            </div>
          </div>

          <div class="header-right">
            <div class="header-actions">
              <button class="header-btn" onclick="toggleEditor()" title="Toggle Editor (Ctrl+E)">
                📝 Editor
              </button>
              <button class="header-btn" onclick="toggleTerminal()" title="Toggle Terminal (Ctrl+T)">
                💻 Terminal
              </button>
              <button class="header-btn deploy-btn" onclick="deployProject()" title="Deploy Project (Ctrl+D)">
                🚀 Deploy
              </button>
            </div>
          </div>
        </header>

        <!-- Main Layout -->
        <div class="ide-layout">
          <!-- Sidebar -->
          <aside class="sidebar" id="sidebar">
            <nav class="sidebar-nav">
              <div class="nav-section">
                <div class="nav-header">Development</div>
                <button class="nav-item ${initialState.activePanel === 'chat' ? 'active' : ''}"
                        onclick="setActivePanel('chat')">
                  💬 Chat
                </button>
                <button class="nav-item ${initialState.activePanel === 'editor' ? 'active' : ''}"
                        onclick="setActivePanel('editor')">
                  📝 Editor
                </button>
                <button class="nav-item ${initialState.activePanel === 'terminal' ? 'active' : ''}"
                        onclick="setActivePanel('terminal')">
                  💻 Terminal
                </button>
              </div>

              <div class="nav-section">
                <div class="nav-header">Resources</div>
                <button class="nav-item ${initialState.activePanel === 'filetree' ? 'active' : ''}"
                        onclick="setActivePanel('filetree')">
                  📁 Files
                </button>
                <button class="nav-item ${initialState.activePanel === 'preview' ? 'active' : ''}"
                        onclick="setActivePanel('preview')">
                  🌐 Preview
                </button>
              </div>

              <div class="nav-section">
                <div class="nav-header">Cloudflare</div>
                <button class="nav-item" onclick="showCloudflareDashboard()">
                  ☁️ Dashboard
                </button>
                <button class="nav-item" onclick="showAnalytics()">
                  📊 Analytics
                </button>
              </div>
            </nav>

            <!-- Ad Sidebar -->
            <div class="ad-sidebar">
              <div class="ad-content">
                <span class="ad-icon">🚀</span>
                <div class="ad-text">
                  <div class="ad-title">Cocapn Pro</div>
                  <div class="ad-description">
                    Unlock unlimited resources and priority support
                  </div>
                  <button class="ad-btn">Upgrade</button>
                </div>
              </div>
            </div>
          </aside>

          <!-- Main Content -->
          <main class="main-content">
            <!-- Chat Panel -->
            <div class="panel chat-panel ${initialState.activePanel === 'chat' ? 'active' : ''}">
              ${ChatInterface.render(config.sessionId, [], false)}
            </div>

            <!-- Editor Panel -->
            <div class="panel editor-panel ${initialState.editorOpen ? 'active' : ''}">
              ${EditorPanel.render([], {})}
            </div>

            <!-- Terminal Panel -->
            <div class="panel terminal-panel ${initialState.terminalOpen ? 'active' : ''}">
              ${TerminalPanel.render({})}
            </div>

            <!-- File Tree Panel -->
            <div class="panel filetree-panel ${initialState.activePanel === 'filetree' ? 'active' : ''}">
              ${FileTree.render(Object.entries(HybridIDE.defaultFiles).map(([path, file]: [string, any]) => ({
                id: path.replace(/\//g, '-'),
                name: file.name,
                path: path,
                type: path.includes('.') ? 'file' : 'folder',
                content: file.content || '',
                modified: Date.now(),
                locked: false
              })), {})}
            </div>

            <!-- Preview Panel -->
            <div class="panel preview-panel ${initialState.activePanel === 'preview' ? 'active' : ''}">
              ${PreviewPanel.render({})}
            </div>
          </main>
        </div>

        <!-- Global Modals -->
        <div id="global-modal" class="modal" style="display: none;">
          <div class="modal-content">
            <span class="close" onclick="closeGlobalModal()">&times;</span>
            <h2 id="modal-title">Modal</h2>
            <div id="modal-body"></div>
            <div class="modal-actions">
              <button class="btn btn-secondary" onclick="closeGlobalModal()">Close</button>
            </div>
          </div>
        </div>

        <style>
          * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
          }

          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: #f5f5f5;
            height: 100vh;
            overflow: hidden;
          }

          .hybrid-ide-container {
            display: flex;
            flex-direction: column;
            height: 100vh;
          }

          /* Header Styles */
          .ide-header {
            background: #ffffff;
            border-bottom: 1px solid #e2e8f0;
            padding: 12px 20px;
            display: flex;
            align-items: center;
            justify-content: space-between;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
            z-index: 100;
            flex-shrink: 0;
          }

          .header-left {
            display: flex;
            align-items: center;
            gap: 16px;
          }

          .menu-toggle {
            background: transparent;
            border: 1px solid #e2e8f0;
            border-radius: 6px;
            padding: 6px 8px;
            cursor: pointer;
            font-size: 16px;
            transition: all 0.2s;
          }

          .menu-toggle:hover {
            background: #f8fafc;
            border-color: #cbd5e1;
          }

          .project-info h1 {
            font-size: 18px;
            font-weight: 600;
            color: #1e293b;
            margin-bottom: 4px;
          }

          .project-status {
            display: flex;
            gap: 12px;
            font-size: 12px;
            color: #64748b;
          }

          .status-ready {
            color: #10b981;
            font-weight: 500;
          }

          .header-center {
            flex: 1;
            display: flex;
            justify-content: center;
          }

          .provider-tabs {
            display: flex;
            gap: 4px;
            background: #f1f5f9;
            padding: 4px;
            border-radius: 8px;
          }

          .provider-tab {
            padding: 6px 12px;
            border: none;
            background: transparent;
            border-radius: 6px;
            cursor: pointer;
            font-size: 12px;
            color: #64748b;
            transition: all 0.2s;
            display: flex;
            align-items: center;
            gap: 4px;
          }

          .provider-tab.active {
            background: #ffffff;
            color: #1e293b;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
          }

          .provider-tab:hover:not(.active) {
            background: #e2e8f0;
            color: #475569;
          }

          .header-right {
            display: flex;
            align-items: center;
            gap: 8px;
          }

          .header-btn {
            padding: 6px 12px;
            border: 1px solid #e2e8f0;
            background: white;
            border-radius: 6px;
            cursor: pointer;
            font-size: 12px;
            color: #475569;
            transition: all 0.2s;
            display: flex;
            align-items: center;
            gap: 4px;
          }

          .header-btn:hover {
            background: #f8fafc;
            border-color: #cbd5e1;
          }

          .deploy-btn {
            background: #10b981;
            color: white;
            border-color: #10b981;
          }

          .deploy-btn:hover {
            background: #059669;
            border-color: #059669;
          }

          /* Layout Styles */
          .ide-layout {
            flex: 1;
            display: flex;
            overflow: hidden;
          }

          .sidebar {
            width: 240px;
            background: #ffffff;
            border-right: 1px solid #e2e8f0;
            display: flex;
            flex-direction: column;
            transition: transform 0.3s ease;
            z-index: 99;
          }

          .sidebar.collapsed {
            transform: translateX(-240px);
          }

          .sidebar-nav {
            flex: 1;
            padding: 12px 0;
            overflow-y: auto;
        }

          .nav-section {
            margin-bottom: 20px;
            padding: 0 12px;
        }

          .nav-header {
            font-size: 11px;
            font-weight: 600;
            color: #94a3b8;
            text-transform: uppercase;
            margin-bottom: 8px;
          }

          .nav-item {
            width: 100%;
            padding: 8px 12px;
            margin-bottom: 2px;
            border: none;
            background: transparent;
            border-radius: 6px;
            cursor: pointer;
            font-size: 13px;
            color: #475569;
            text-align: left;
            transition: all 0.2s;
            display: flex;
            align-items: center;
            gap: 8px;
          }

          .nav-item:hover {
            background: #f1f5f9;
            color: #1e293b;
          }

          .nav-item.active {
            background: #e0f2fe;
            color: #0c4a6e;
            font-weight: 500;
          }

          .ad-sidebar {
            border-top: 1px solid #e2e8f0;
            padding: 12px;
            background: #f8fafc;
        }

          .ad-content {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            padding: 12px;
            border-radius: 8px;
            color: white;
            text-align: center;
          }

          .ad-icon {
            font-size: 24px;
            margin-bottom: 8px;
          }

          .ad-title {
            font-weight: 600;
            font-size: 14px;
            margin-bottom: 4px;
          }

          .ad-description {
            font-size: 11px;
            opacity: 0.9;
            margin-bottom: 8px;
          }

          .ad-btn {
            background: rgba(255, 255, 255, 0.2);
            border: 1px solid rgba(255, 255, 255, 0.3);
            color: white;
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 11px;
            cursor: pointer;
            transition: all 0.2s;
          }

          .ad-btn:hover {
            background: rgba(255, 255, 255, 0.3);
          }

          .main-content {
            flex: 1;
            display: flex;
            flex-direction: column;
            overflow: hidden;
            position: relative;
        }

          /* Panel Styles */
          .panel {
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background: #ffffff;
            border: 1px solid #e2e8f0;
            border-radius: 8px;
            margin: 12px;
            overflow: hidden;
            transition: opacity 0.3s ease, transform 0.3s ease;
        }

          .panel.active {
            opacity: 1;
            transform: none;
            z-index: 10;
          }

          .panel:not(.active) {
            opacity: 0;
            transform: scale(0.95);
            pointer-events: none;
            z-index: 1;
          }

          /* Responsive Design */
          @media (max-width: 768px) {
            .ide-header {
              padding: 8px 12px;
              flex-wrap: wrap;
              gap: 8px;
            }

            .header-left {
              order: 1;
              width: 100%;
              justify-content: space-between;
            }

            .header-center {
              order: 3;
              width: 100%;
              margin-top: 8px;
            }

            .header-right {
              order: 2;
              width: 100%;
              justify-content: space-between;
            }

            .sidebar {
              width: 200px;
            }

            .panel {
              margin: 4px;
            }

            .ad-sidebar {
              display: none;
            }
          }

          @media (max-width: 640px) {
            .sidebar {
              position: fixed;
              left: 0;
              top: 0;
              bottom: 0;
              z-index: 1000;
              box-shadow: 2px 0 8px rgba(0, 0, 0, 0.1);
            }

            .main-content {
              margin-left: 0;
            }

            .provider-tabs {
              flex-wrap: wrap;
            }

            .panel {
              border-radius: 0;
              margin: 0;
              border: none;
              border-top: 1px solid #e2e8f0;
            }
          }

          /* Modal Styles */
          .modal {
            display: none;
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: rgba(0, 0, 0, 0.5);
            z-index: 2000;
            animation: fadeIn 0.2s ease-out;
          }

          .modal.show {
            display: flex;
            align-items: center;
            justify-content: center;
          }

          .modal-content {
            background: white;
            border: 1px solid #e2e8f0;
            border-radius: 12px;
            padding: 24px;
            max-width: 500px;
            width: 90%;
            box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1);
            animation: slideUp 0.3s ease-out;
        }

          .modal-content h2 {
            margin: 0 0 16px 0;
            color: #1e293b;
            font-size: 18px;
        }

          @keyframes fadeIn {
            from { opacity: 0; }
            to { opacity: 1; }
          }

          @keyframes slideUp {
            from {
              opacity: 0;
              transform: translateY(20px);
            }
            to {
              opacity: 1;
              transform: translateY(0);
            }
          }

          .modal .close {
            position: absolute;
            top: 12px;
            right: 12px;
            font-size: 24px;
            cursor: pointer;
            color: #94a3b8;
            border: none;
            background: transparent;
            padding: 0;
            width: 32px;
            height: 32px;
            display: flex;
            align-items: center;
            justify-content: center;
            border-radius: 6px;
            transition: all 0.2s;
          }

          .modal .close:hover {
            background: #f1f5f9;
            color: #334155;
          }

          .modal-actions {
            display: flex;
            gap: 8px;
            margin-top: 20px;
            justify-content: flex-end;
          }

          .btn {
            padding: 8px 16px;
            border: 1px solid #e2e8f0;
            border-radius: 6px;
            cursor: pointer;
            font-size: 12px;
            font-weight: 500;
            transition: all 0.2s;
        }

          .btn-primary {
            background: #3b82f6;
            color: white;
            border-color: #3b82f6;
          }

          .btn-primary:hover {
            background: #2563eb;
            border-color: #2563eb;
          }

          .btn-secondary {
            background: white;
            color: #475569;
            border-color: #e2e8f0;
          }

          .btn-secondary:hover {
            background: #f8fafc;
            border-color: #cbd5e1;
          }
        </style>

        <script>
          // Global IDE state
          let ideState = {
            sidebarOpen: true,
            editorOpen: false,
            terminalOpen: false,
            activePanel: 'chat',
            currentProvider: 'manus',
            sessionId: '${config.sessionId}',
            project: ${JSON.stringify(config.project)}
          };

          // Toggle sidebar
          function toggleSidebar() {
            ideState.sidebarOpen = !ideState.sidebarOpen;
            const sidebar = document.getElementById('sidebar');
            sidebar.classList.toggle('collapsed', !ideState.sidebarOpen);
          }

          // Toggle editor
          function toggleEditor() {
            ideState.editorOpen = !ideState.editorOpen;
            const editorPanel = document.querySelector('.editor-panel');
            if (editorPanel) {
              editorPanel.classList.toggle('active', ideState.editorOpen);
            }
          }

          // Toggle terminal
          function toggleTerminal() {
            ideState.terminalOpen = !ideState.terminalOpen;
            const terminalPanel = document.querySelector('.terminal-panel');
            if (terminalPanel) {
              terminalPanel.classList.toggle('active', ideState.terminalOpen);
            }
          }

          // Switch provider
          function switchProvider(providerId) {
            ideState.currentProvider = providerId;
            // Update provider tabs
            document.querySelectorAll('.provider-tab').forEach(tab => {
              tab.classList.remove('active');
            });
            const activeTab = Array.from(document.querySelectorAll('.provider-tab')).find(
              tab => tab.textContent.includes(unescapeHtml(providerId))
            );
            if (activeTab) {
              activeTab.classList.add('active');
            }

            // Update state
            updateProviderState(providerId);
          }

          // Set active panel
          function setActivePanel(panel) {
            ideState.activePanel = panel;

            // Update nav items
            document.querySelectorAll('.nav-item').forEach(item => {
              item.classList.remove('active');
            });
            event.target.classList.add('active');

            // Update panels
            document.querySelectorAll('.panel').forEach(panelElement => {
              panelElement.classList.remove('active');
            });
            const activePanel = document.querySelector(\`.${panel}-panel\`);
            if (activePanel) {
              activePanel.classList.add('active');
            }
          }

          // Deploy project
          async function deployProject() {
            const modal = document.getElementById('global-modal');
            const modalBody = document.getElementById('modal-body');

            const modalContent = document.createElement('div');
            modalContent.style.cssText = 'text-align: center; padding: 20px;';

            const rocketDiv = document.createElement('div');
            rocketDiv.style.cssText = 'font-size: 48px; margin-bottom: 16px;';
            rocketDiv.textContent = '🚀';

            const titleH3 = document.createElement('h3');
            titleH3.textContent = 'Deploying Project';

            const descriptionP = document.createElement('p');
            descriptionP.style.cssText = 'color: #64748b; margin-top: 8px;';
            descriptionP.textContent = 'Your project is being deployed to Cloudflare Workers...';

            const progressContainer = document.createElement('div');
            progressContainer.style.cssText = 'margin-top: 20px;';

            const progressBar = document.createElement('div');
            progressBar.style.cssText = 'width: 200px; height: 4px; background: #e2e8f0; border-radius: 2px; margin: 0 auto;';

            const progressFill = document.createElement('div');
            progressFill.id = 'deploy-progress';
            progressFill.style.cssText = 'width: 0%; height: 100%; background: #10b981; border-radius: 2px; transition: width 0.3s ease;';

            progressBar.appendChild(progressFill);
            progressContainer.appendChild(progressBar);
            modalContent.appendChild(rocketDiv);
            modalContent.appendChild(titleH3);
            modalContent.appendChild(descriptionP);
            modalContent.appendChild(progressContainer);

            modalBody.innerHTML = '';
            modalBody.appendChild(modalContent);

            modal.classList.add('show');

            // Simulate deployment progress
            let progress = 0;
            const interval = setInterval(() => {
              progress += Math.random() * 20;
              if (progress >= 100) {
                progress = 100;
                clearInterval(interval);

                // Show success message
                setTimeout(() => {
                  modalBody.innerHTML = '';

                  const successContent = document.createElement('div');
                  successContent.style.cssText = 'text-align: center; padding: 20px;';

                  const successIcon = document.createElement('div');
                  successIcon.style.cssText = 'font-size: 48px; margin-bottom: 16px;';
                  successIcon.textContent = '✅';

                  const successTitle = document.createElement('h3');
                  successTitle.textContent = 'Deployment Successful!';

                  const successDesc = document.createElement('p');
                  successDesc.style.cssText = 'color: #64748b; margin-top: 8px;';
                  successDesc.textContent = 'Your project is now live at:';

                  const urlDiv = document.createElement('div');
                  urlDiv.style.cssText = 'background: #f8fafc; padding: 12px; border-radius: 6px; margin: 16px 0; font-family: monospace; font-size: 14px;';
                  urlDiv.textContent = 'https://' + (ideState.project?.name || 'my-project') + '.cocapn.workers.dev';

                  const openBtn = document.createElement('button');
                  openBtn.style.cssText = 'background: #10b981; color: white; border: none; padding: 8px 16px; border-radius: 6px; cursor: pointer; margin-top: 16px;';
                  openBtn.textContent = 'Open in New Tab';
                  openBtn.onclick = openInNewTab;

                  successContent.appendChild(successIcon);
                  successContent.appendChild(successTitle);
                  successContent.appendChild(successDesc);
                  successContent.appendChild(urlDiv);
                  successContent.appendChild(openBtn);

                  modalBody.appendChild(successContent);
                }, 500);
              }
              progressFill.style.width = progress + '%';
            }, 300);
          }

          // Open in new tab
          function openInNewTab() {
            const url = document.getElementById('deploy-progress').parentElement.parentElement.querySelector('div').textContent;
            window.open(url, '_blank');
            closeGlobalModal();
          }

          // Close global modal
          function closeGlobalModal() {
            const modal = document.getElementById('global-modal');
            modal.classList.remove('show');
          }

          // Show Cloudflare Dashboard
          function showCloudflareDashboard() {
            showGlobalModal('Cloudflare Dashboard', \`
              <div style="text-align: center; padding: 20px;">
                <div style="font-size: 48px; margin-bottom: 16px;">☁️</div>
                <h3>Cloudflare Dashboard</h3>
                <p style="color: #64748b; margin-top: 8px;">View your Workers, analytics, and settings</p>
                <button onclick="window.open('https://dash.cloudflare.com/', '_blank')" style="background: #10b981; color: white; border: none; padding: 8px 16px; border-radius: 6px; cursor: pointer; margin-top: 16px;">Open Dashboard</button>
              </div>
            \`);
          }

          // Show Analytics
          function showAnalytics() {
            showGlobalModal('Project Analytics', \`
              <div style="padding: 20px;">
                <h3 style="margin-bottom: 16px;">Project Analytics</h3>
                <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 16px;">
                  <div style="background: #f8fafc; padding: 12px; border-radius: 6px; text-align: center;">
                    <div style="font-size: 24px; font-weight: bold; color: #10b981;">1,234</div>
                    <div style="color: #64748b; font-size: 12px;">Requests Today</div>
                  </div>
                  <div style="background: #f8fafc; padding: 12px; border-radius: 6px; text-align: center;">
                    <div style="font-size: 24px; font-weight: bold; color: #3b82f6;">45ms</div>
                    <div style="color: #64748b; font-size: 12px;">Avg Response Time</div>
                  </div>
                </div>
                <div style="background: #f8fafc; padding: 12px; border-radius: 6px;">
                  <div style="color: #64748b; font-size: 12px; margin-bottom: 4px;">Error Rate</div>
                  <div style="font-weight: bold; color: #10b981;">0.2%</div>
                </div>
              </div>
            \`);
          }

          // Show global modal
          function showGlobalModal(title, content) {
            const modal = document.getElementById('global-modal');
            const modalTitle = document.getElementById('modal-title');
            const modalBody = document.getElementById('modal-body');

            modalTitle.textContent = title;
            modalBody.innerHTML = content;
            modal.classList.add('show');
          }

          // Update provider state
          async function updateProviderState(providerId) {
            // Notify all panels about provider change
            window.dispatchEvent(new CustomEvent('providerChanged', {
              detail: { providerId }
            }));

            // Update UI
            console.log('Provider switched to:', providerId);
          }

          // Keyboard shortcuts
          document.addEventListener('keydown', (event) => {
            const ctrlKey = event.ctrlKey || event.metaKey;

            // Ctrl+E: Toggle Editor
            if (ctrlKey && event.key.toLowerCase() === 'e') {
              event.preventDefault();
              toggleEditor();
            }

            // Ctrl+T: Toggle Terminal
            if (ctrlKey && event.key.toLowerCase() === 't') {
              event.preventDefault();
              toggleTerminal();
            }

            // Ctrl+D: Deploy
            if (ctrlKey && event.key.toLowerCase() === 'd') {
              event.preventDefault();
              deployProject();
            }

            // Ctrl+B: Toggle Sidebar
            if (ctrlKey && event.key.toLowerCase() === 'b') {
              event.preventDefault();
              toggleSidebar();
            }

            // Escape: Close modal
            if (event.key === 'Escape' && document.getElementById('global-modal').classList.contains('show')) {
              closeGlobalModal();
            }
          });

          // Handle provider-specific actions
          window.addEventListener('providerChanged', (event) => {
            // Update all components with new provider
            console.log('Provider changed to:', event.detail.providerId);

            // Update chat provider
            if (window.currentProvider !== event.detail.providerId) {
              window.currentProvider = event.detail.providerId;
            }
          });

          // Utility functions
          function escapeHtml(text) {
            const div = document.createElement('div');
            div.textContent = text;
            return div.innerHTML;
          }

          function unescapeHtml(html) {
            const div = document.createElement('div');
            div.innerHTML = html;
            return div.textContent;
          }

          // Initialize IDE
          document.addEventListener('DOMContentLoaded', () => {
            // Set initial active provider
            updateProviderState(ideState.currentProvider);

            // Set default panel as active
            setActivePanel(ideState.activePanel);

            // Load project files if available
            if (ideState.project?.files) {
              // Initialize file tree with project files
              window.dispatchEvent(new CustomEvent('projectLoaded', {
                detail: { files: ideState.project.files }
              }));
            }

            console.log('Cocapn Hybrid IDE initialized successfully');
          });
        </script>
      </div>
    `;
  },
};