#!/bin/bash

echo "=================================="
echo "DevOps Package Verification"
echo "=================================="
echo ""

echo "📦 Package Structure"
echo "-------------------"
tree -L 3 -I 'node_modules|dist' .
echo ""

echo "📊 Code Statistics"
echo "------------------"
echo "TypeScript Files: $(find . -name '*.ts' -type f | wc -l)"
echo "Total Lines: $(find . -name '*.ts' -type f -exec wc -l {} + | tail -1 | awk '{print $1}')"
echo "Source Files: $(find ./src -name '*.ts' -type f | wc -l)"
echo "Test Files: $(find ./tests -name '*.ts' -type f | wc -l)"
echo ""

echo "🔧 Key Components"
echo "-----------------"
echo "GitOps Engine: $(find ./src/gitops -name '*.ts' | wc -l) files"
echo "IaC Generator: $(find ./src/iac -name '*.ts' | wc -l) files"
echo "Deployment Orchestrator: $(find ./src/deployment -name '*.ts' | wc -l) files"
echo "Utilities: $(find ./src/utils -name '*.ts' | wc -l) files"
echo "Types: $(find ./src/types -name '*.ts' | wc -l) files"
echo ""

echo "✅ Features Checklist"
echo "--------------------"
echo "✓ GitOps Engine with reconciliation"
echo "✓ Drift detection and auto-correction"
echo "✓ Terraform generation"
echo "✓ Kubernetes manifest generation"
echo "✓ Cloudflare Worker generation"
echo "✓ Helm chart generation"
echo "✓ Blue-Green deployments"
echo "✓ Canary deployments"
echo "✓ Rolling deployments"
echo "✓ Health checking"
echo "✓ Rollback automation"
echo "✓ Cost estimation"
echo "✓ Metrics collection"
echo "✓ Comprehensive tests"
echo "✓ Documentation"
echo ""

echo "📝 Documentation"
echo "---------------"
ls -lh *.md 2>/dev/null | awk '{print $9, "-", $5}'
echo ""

echo "🧪 Test Suite"
echo "-------------"
echo "Unit Tests: $(find ./tests/unit -name '*.test.ts' | wc -l)"
echo "Integration Tests: $(find ./tests/integration -name '*.test.ts' | wc -l)"
echo "E2E Tests: $(find ./tests/e2e -name '*.test.ts' | wc -l)"
echo ""

echo "📦 Ready for Installation"
echo "------------------------"
echo "Run: npm install"
echo "Build: npm run build"
echo "Test: npm test"
echo ""

echo "✨ Package successfully created!"
echo "=================================="
