/**
 * IaC Generator - Generate Terraform, Kubernetes, and Cloudflare IaC
 */

import {
  IaCConfig,
  TerraformModule,
  KubernetesManifest,
  CloudflareWorkerConfig,
  CostEstimate,
  CostBreakdown,
  DeploymentConfig,
  Environment,
} from '../types';
import { Logger } from '../utils/logger';
import { TemplateEngine } from '../utils/template-engine';
import { Validator } from '../utils/validator';
import { computeCostEstimate } from '../utils/cost-calculator';
import * as yaml from 'yaml';
import * as fs from 'fs/promises';

export interface IaCGenerationOptions {
  config: IaCConfig;
  outputPath?: string;
  includeComments?: boolean;
  formatOutput?: boolean;
  validate?: boolean;
}

export interface IaCGenerationResult {
  success: boolean;
  outputPath?: string;
  files: string[];
  errors?: string[];
  costEstimate?: CostEstimate;
}

export interface TerraformOutput {
  main: string;
  variables: string;
  outputs: string;
  providers: string;
  modules: Map<string, string>;
}

/**
 * Main IaC Generator class
 */
export class IaCGenerator {
  private logger: Logger;
  private templateEngine: TemplateEngine;
  private validator: Validator;

  constructor(logger?: Logger) {
    this.logger = logger || new Logger({ service: 'iac-generator' });
    this.templateEngine = new TemplateEngine(this.logger);
    this.validator = new Validator(this.logger);
  }

  /**
   * Generate IaC based on configuration
   */
  async generate(
    options: IaCGenerationOptions
  ): Promise<IaCGenerationResult> {
    const startTime = Date.now();
    const result: IaCGenerationResult = {
      success: false,
      files: [],
    };

    try {
      this.logger.info('Starting IaC generation', {
        type: options.config.type,
      });

      // Validate configuration
      if (options.validate) {
        await this.validateConfig(options.config);
      }

      let output: any;

      switch (options.config.type) {
        case 'terraform':
          output = await this.generateTerraform(options);
          break;
        case 'kubernetes':
          output = await this.generateKubernetes(options);
          break;
        case 'cloudflare':
          output = await this.generateCloudflare(options);
          break;
        case 'helm':
          output = await this.generateHelm(options);
          break;
        default:
          throw new Error(`Unsupported IaC type: ${options.config.type}`);
      }

      // Write output if path is specified
      if (options.outputPath) {
        await this.writeOutput(output, options.outputPath);
        result.outputPath = options.outputPath;
      }

      // Generate cost estimate
      result.costEstimate = await computeCostEstimate(options.config);

      result.success = true;
      result.files = Object.keys(output);

      const duration = Date.now() - startTime;
      this.logger.info('IaC generation completed', {
        type: options.config.type,
        fileCount: result.files.length,
        duration,
      });

      return result;
    } catch (error: any) {
      this.logger.error('IaC generation failed', { error: error.message });
      result.errors = [error.message];
      return result;
    }
  }

  /**
   * Generate Terraform configuration
   */
  private async generateTerraform(
    options: IaCGenerationOptions
  ): Promise<Record<string, string>> {
    const config = options.config;
    const files: Record<string, string> = {};

    // Generate main.tf
    files['main.tf'] = this.generateTerraformMain(config);

    // Generate variables.tf
    files['variables.tf'] = this.generateTerraformVariables(config);

    // Generate outputs.tf
    files['outputs.tf'] = this.generateTerraformOutputs(config);

    // Generate providers.tf
    files['providers.tf'] = this.generateTerraformProviders(config);

    // Generate terraform.tfvars with default values
    files['terraform.tfvars'] = this.generateTerraformTfvars(config);

    // Generate modules
    if (config.variables?.modules) {
      for (const [name, module] of Object.entries(
        config.variables.modules as Record<string, TerraformModule>
      )) {
        const modulePath = `modules/${name}`;
        files[`${modulePath}/main.tf`] = this.generateModuleMain(module);
        files[`${modulePath}/variables.tf`] = this.generateModuleVariables(
          module
        );
        files[`${modulePath}/outputs.tf`] = this.generateModuleOutputs(module);
      }
    }

    return files;
  }

  /**
   * Generate Terraform main configuration
   */
  private generateTerraformMain(config: IaCConfig): string {
    const lines: string[] = [];

    lines.push('# Terraform configuration generated by ClaudeFlare');
    lines.push('# Generated at: ' + new Date().toISOString());
    lines.push('');

    // Terraform block
    lines.push('terraform {');
    lines.push(`  required_version = ">= 1.0"`);
    lines.push('');

    if (config.backend) {
      lines.push('  backend "' + config.backend.type + '" {');
      for (const [key, value] of Object.entries(config.backend.config)) {
        lines.push(`    ${key} = ${this.formatTerraformValue(value)}`);
      }
      lines.push('  }');
      lines.push('');
    }

    if (config.variables?.modules) {
      lines.push('  required_providers {');
      const providers = new Set<string>();
      for (const module of Object.values(
        config.variables.modules as Record<string, TerraformModule>
      )) {
        // Extract provider from module source
        const match = module.source.match(/^([^/]+)/);
        if (match) {
          providers.add(match[1]);
        }
      }
      for (const provider of providers) {
        lines.push(`    ${provider} = {`);
        lines.push(`      source  = "hashicorp/${provider}"`);
        lines.push(`    }`);
      }
      lines.push('  }');
    }

    lines.push('}');
    lines.push('');

    // Module blocks
    if (config.variables?.modules) {
      for (const [name, module] of Object.entries(
        config.variables.modules as Record<string, TerraformModule>
      )) {
        lines.push(`module "${name}" {`);
        lines.push(`  source = "${module.source}"`);

        if (module.version) {
          lines.push(`  version = "${module.version}"`);
        }

        // Variables
        for (const [key, value] of Object.entries(module.variables)) {
          lines.push(`  ${key} = ${this.formatTerraformValue(value)}`);
        }

        if (module.dependsOn && module.dependsOn.length > 0) {
          lines.push(`  depends_on = [${module.dependsOn.map((d) => `"${d}"`).join(', ')}]`);
        }

        lines.push('}');
        lines.push('');
      }
    }

    // Provider-specific resources
    if (config.providers) {
      for (const provider of config.providers) {
        lines.push(this.generateProviderResources(provider));
      }
    }

    return lines.join('\n');
  }

  /**
   * Generate Terraform variables
   */
  private generateTerraformVariables(config: IaCConfig): string {
    const lines: string[] = [];

    lines.push('# Input variables');
    lines.push('');

    // Common variables
    const commonVars = [
      { name: 'environment', type: 'string', description: 'Deployment environment' },
      { name: 'project_name', type: 'string', description: 'Project name' },
      { name: 'region', type: 'string', description: 'Cloud region' },
    ];

    for (const v of commonVars) {
      lines.push(`variable "${v.name}" {`);
      lines.push(`  type        = ${v.type}`);
      lines.push(`  description = "${v.description}"`);
      lines.push('}');
      lines.push('');
    }

    // Provider-specific variables
    if (config.providers) {
      for (const provider of config.providers) {
        for (const [key, value] of Object.entries(provider.configuration)) {
          if (key.includes('key') || key.includes('secret') || key.includes('token')) {
            lines.push(`variable "${provider.name}_${key}" {`);
            lines.push(`  type        = string`);
            lines.push(`  description = "${provider.name} ${key}"`);
            lines.push(`  sensitive   = true`);
            lines.push('}');
            lines.push('');
          }
        }
      }
    }

    return lines.join('\n');
  }

  /**
   * Generate Terraform outputs
   */
  private generateTerraformOutputs(config: IaCConfig): string {
    const lines: string[] = [];

    lines.push('# Output values');
    lines.push('');

    if (config.outputs) {
      for (const output of config.outputs) {
        lines.push(`output "${output}" {`);
        lines.push(`  description = "Output for ${output}"`);
        lines.push(`  value       = try(module.main.${output}, null)`);
        lines.push('}');
        lines.push('');
      }
    }

    return lines.join('\n');
  }

  /**
   * Generate Terraform providers configuration
   */
  private generateTerraformProviders(config: IaCConfig): string {
    const lines: string[] = [];

    lines.push('# Provider configurations');
    lines.push('');

    if (config.providers) {
      for (const provider of config.providers) {
        lines.push(`provider "${provider.name}" {`);
        for (const [key, value] of Object.entries(provider.configuration)) {
          lines.push(`  ${key} = ${this.formatTerraformValue(value)}`);
        }
        lines.push('}');
        lines.push('');
      }
    }

    return lines.join('\n');
  }

  /**
   * Generate terraform.tfvars
   */
  private generateTerraformTfvars(config: IaCConfig): string {
    const lines: string[] = [];

    lines.push('# Terraform variable values');
    lines.push('# DO NOT commit sensitive values to version control');
    lines.push('');

    if (config.variables) {
      for (const [key, value] of Object.entries(config.variables)) {
        if (key !== 'modules') {
          lines.push(`${key} = ${this.formatTerraformValue(value)}`);
        }
      }
    }

    return lines.join('\n');
  }

  /**
   * Generate module main.tf
   */
  private generateModuleMain(module: TerraformModule): string {
    const lines: string[] = [];

    lines.push(`# Module: ${module.name}`);
    lines.push(`# Source: ${module.source}`);
    lines.push('');

    lines.push('resource "example_resource" "this" {');
    lines.push('  # Module resources');
    lines.push('}');

    return lines.join('\n');
  }

  /**
   * Generate module variables.tf
   */
  private generateModuleVariables(module: TerraformModule): string {
    const lines: string[] = [];

    for (const [key, value] of Object.entries(module.variables)) {
      const type = this.inferTerraformType(value);
      lines.push(`variable "${key}" {`);
      lines.push(`  type = ${type}`);
      lines.push(`  description = "Module variable ${key}"`);
      lines.push('}');
      lines.push('');
    }

    return lines.join('\n');
  }

  /**
   * Generate module outputs.tf
   */
  private generateModuleOutputs(module: TerraformModule): string {
    const lines: string[] = [];

    lines.push('output "id" {');
    lines.push('  description = "Resource ID"');
    lines.push('  value       = try(resource.example_resource.this.id, null)');
    lines.push('}');

    return lines.join('\n');
  }

  /**
   * Generate provider resources
   */
  private generateProviderResources(provider: any): string {
    const lines: string[] = [];

    lines.push(`# Resources for ${provider.name}`);
    lines.push('');

    // Generate provider-specific resources
    switch (provider.name) {
      case 'cloudflare':
        lines.push(this.generateCloudflareResources(provider));
        break;
      case 'kubernetes':
        lines.push(this.generateKubernetesResources(provider));
        break;
      case 'aws':
        lines.push(this.generateAWSResources(provider));
        break;
      default:
        lines.push(`# No specific resources for ${provider.name}`);
    }

    return lines.join('\n');
  }

  /**
   * Generate Cloudflare resources
   */
  private generateCloudflareResources(provider: any): string {
    const lines: string[] = [];

    lines.push('resource "cloudflare_worker_script" "main" {');
    lines.push('  name    = var.project_name');
    lines.push('  content = file("${path.module}/worker.js")');
    lines.push('}');
    lines.push('');

    lines.push('resource "cloudflare_workers_kv_namespace" "this" {');
    lines.push('  title = "${var.project_name}-kv"');
    lines.push('}');
    lines.push('');

    lines.push('resource "cloudflare_r2_bucket" "this" {');
    lines.push('  account_id = var.cloudflare_account_id');
    lines.push('  name       = "${var.project_name}-r2"');
    lines.push('}');

    return lines.join('\n');
  }

  /**
   * Generate Kubernetes resources
   */
  private generateKubernetesResources(provider: any): string {
    const lines: string[] = [];

    lines.push('resource "kubernetes_deployment" "main" {');
    lines.push('  metadata {');
    lines.push('    name = var.project_name');
    lines.push('    labels = {');
    lines.push('      app = var.project_name');
    lines.push('    }');
    lines.push('  }');
    lines.push('');
    lines.push('  spec {');
    lines.push('    replicas = 3');
    lines.push('');
    lines.push('    selector {');
    lines.push('      match_labels = {');
    lines.push('        app = var.project_name');
    lines.push('      }');
    lines.push('    }');
    lines.push('');
    lines.push('    template {');
    lines.push('      metadata {');
    lines.push('        labels = {');
    lines.push('          app = var.project_name');
    lines.push('        }');
    lines.push('      }');
    lines.push('');
    lines.push('      spec {');
    lines.push('        container {');
    lines.push('          name  = "app"');
    lines.push('          image = "${var.project_name}:latest"');
    lines.push('        }');
    lines.push('      }');
    lines.push('    }');
    lines.push('  }');
    lines.push('}');
    lines.push('');

    lines.push('resource "kubernetes_service" "main" {');
    lines.push('  metadata {');
    lines.push('    name = var.project_name');
    lines.push('  }');
    lines.push('');
    lines.push('  spec {');
    lines.push('    selector = {');
    lines.push('      app = var.project_name');
    lines.push('    }');
    lines.push('');
    lines.push('    port {');
    lines.push('      port        = 80');
    lines.push('      target_port = 8080');
    lines.push('    }');
    lines.push('');
    lines.push('    type = "LoadBalancer"');
    lines.push('  }');
    lines.push('}');

    return lines.join('\n');
  }

  /**
   * Generate AWS resources
   */
  private generateAWSResources(provider: any): string {
    const lines: string[] = [];

    lines.push('resource "aws_s3_bucket" "this" {');
    lines.push('  bucket = "${var.project_name}-${var.environment}"');
    lines.push('}');
    lines.push('');

    lines.push('resource "aws_lambda_function" "main" {');
    lines.push('  function_name = var.project_name');
    lines.push('  s3_bucket     = aws_s3_bucket.this.id');
    lines.push('  s3_key        = "function.zip"');
    lines.push('  handler       = "index.handler"');
    lines.push('  runtime       = "nodejs18.x"');
    lines.push('');
    lines.push('  environment {');
    lines.push('    variables = {');
    lines.push('      ENVIRONMENT = var.environment');
    lines.push('    }');
    lines.push('  }');
    lines.push('}');

    return lines.join('\n');
  }

  /**
   * Generate Kubernetes manifests
   */
  private async generateKubernetes(
    options: IaCGenerationOptions
  ): Promise<Record<string, string>> {
    const config = options.config;
    const files: Record<string, string> = {};

    // Generate common manifests
    files['namespace.yaml'] = this.generateNamespaceManifest(config);
    files['deployment.yaml'] = this.generateDeploymentManifest(config);
    files['service.yaml'] = this.generateServiceManifest(config);
    files['configmap.yaml'] = this.generateConfigMapManifest(config);
    files['ingress.yaml'] = this.generateIngressManifest(config);

    // Generate HPA if enabled
    if (config.variables?.enableHpa) {
      files['hpa.yaml'] = this.generateHPAManifest(config);
    }

    // Generate PodDisruptionBudget if enabled
    if (config.variables?.enablePdb) {
      files['pdb.yaml'] = this.generatePDBManifest(config);
    }

    return files;
  }

  /**
   * Generate namespace manifest
   */
  private generateNamespaceManifest(config: IaCConfig): string {
    const manifest: KubernetesManifest = {
      apiVersion: 'v1',
      kind: 'Namespace',
      metadata: {
        name: config.variables?.namespace || 'default',
        labels: {
          'name': config.variables?.namespace || 'default',
          'managed-by': 'claudeflare',
        },
      },
    };

    return yaml.stringify(manifest);
  }

  /**
   * Generate deployment manifest
   */
  private generateDeploymentManifest(config: IaCConfig): string {
    const namespace = config.variables?.namespace || 'default';
    const appName = config.variables?.appName || 'app';
    const replicas = config.variables?.replicas || 3;
    const image = config.variables?.image || 'nginx:latest';

    const manifest: KubernetesManifest = {
      apiVersion: 'apps/v1',
      kind: 'Deployment',
      metadata: {
        name: appName,
        namespace,
        labels: {
          app: appName,
          'managed-by': 'claudeflare',
        },
      },
      spec: {
        replicas,
        selector: {
          matchLabels: {
            app: appName,
          },
        },
        template: {
          metadata: {
            labels: {
              app: appName,
            },
          },
          spec: {
            containers: [
              {
                name: appName,
                image,
                ports: [
                  {
                    containerPort: config.variables?.containerPort || 8080,
                  },
                ],
                resources: config.variables?.resources || {
                  requests: {
                    cpu: '100m',
                    memory: '128Mi',
                  },
                  limits: {
                    cpu: '500m',
                    memory: '512Mi',
                  },
                },
                env: config.variables?.env || [],
              },
            ],
          },
        },
      },
    };

    return yaml.stringify(manifest);
  }

  /**
   * Generate service manifest
   */
  private generateServiceManifest(config: IaCConfig): string {
    const namespace = config.variables?.namespace || 'default';
    const appName = config.variables?.appName || 'app';
    const serviceType = config.variables?.serviceType || 'ClusterIP';

    const manifest: KubernetesManifest = {
      apiVersion: 'v1',
      kind: 'Service',
      metadata: {
        name: appName,
        namespace,
        labels: {
          app: appName,
          'managed-by': 'claudeflare',
        },
      },
      spec: {
        type: serviceType,
        selector: {
          app: appName,
        },
        ports: [
          {
            port: config.variables?.servicePort || 80,
            targetPort: config.variables?.containerPort || 8080,
            protocol: 'TCP',
          },
        ],
      },
    };

    return yaml.stringify(manifest);
  }

  /**
   * Generate ConfigMap manifest
   */
  private generateConfigMapManifest(config: IaCConfig): string {
    const namespace = config.variables?.namespace || 'default';
    const appName = config.variables?.appName || 'app';

    const manifest: KubernetesManifest = {
      apiVersion: 'v1',
      kind: 'ConfigMap',
      metadata: {
        name: `${appName}-config`,
        namespace,
        labels: {
          app: appName,
          'managed-by': 'claudeflare',
        },
      },
      data: config.variables?.configData || {
        'config.yaml': '{}',
      },
    };

    return yaml.stringify(manifest);
  }

  /**
   * Generate Ingress manifest
   */
  private generateIngressManifest(config: IaCConfig): string {
    const namespace = config.variables?.namespace || 'default';
    const appName = config.variables?.appName || 'app';
    const host = config.variables?.ingressHost || 'app.example.com';

    const manifest: KubernetesManifest = {
      apiVersion: 'networking.k8s.io/v1',
      kind: 'Ingress',
      metadata: {
        name: appName,
        namespace,
        labels: {
          app: appName,
          'managed-by': 'claudeflare',
        },
        annotations: config.variables?.ingressAnnotations || {
          'kubernetes.io/ingress.class': 'nginx',
          'cert-manager.io/cluster-issuer': 'letsencrypt-prod',
        },
      },
      spec: {
        rules: [
          {
            host,
            http: {
              paths: [
                {
                  path: '/',
                  pathType: 'Prefix',
                  backend: {
                    service: {
                      name: appName,
                      port: {
                        number: config.variables?.servicePort || 80,
                      },
                    },
                  },
                },
              ],
            },
          },
        ],
        tls: config.variables?.tlsEnabled
          ? [
              {
                hosts: [host],
                secretName: `${appName}-tls`,
              },
            ]
          : undefined,
      },
    };

    return yaml.stringify(manifest);
  }

  /**
   * Generate HPA manifest
   */
  private generateHPAManifest(config: IaCConfig): string {
    const namespace = config.variables?.namespace || 'default';
    const appName = config.variables?.appName || 'app';

    const manifest: KubernetesManifest = {
      apiVersion: 'autoscaling/v2',
      kind: 'HorizontalPodAutoscaler',
      metadata: {
        name: appName,
        namespace,
        labels: {
          app: appName,
          'managed-by': 'claudeflare',
        },
      },
      spec: {
        scaleTargetRef: {
          apiVersion: 'apps/v1',
          kind: 'Deployment',
          name: appName,
        },
        minReplicas: config.variables?.hpaMinReplicas || 2,
        maxReplicas: config.variables?.hpaMaxReplicas || 10,
        metrics: config.variables?.hpaMetrics || [
          {
            type: 'Resource',
            resource: {
              name: 'cpu',
              target: {
                type: 'Utilization',
                averageUtilization: 80,
              },
            },
          },
        ],
      },
    };

    return yaml.stringify(manifest);
  }

  /**
   * Generate PodDisruptionBudget manifest
   */
  private generatePDBManifest(config: IaCConfig): string {
    const namespace = config.variables?.namespace || 'default';
    const appName = config.variables?.appName || 'app';

    const manifest: KubernetesManifest = {
      apiVersion: 'policy/v1',
      kind: 'PodDisruptionBudget',
      metadata: {
        name: appName,
        namespace,
        labels: {
          app: appName,
          'managed-by': 'claudeflare',
        },
      },
      spec: {
        minAvailable: config.variables?.pdbMinAvailable || 1,
        selector: {
          matchLabels: {
            app: appName,
          },
        },
      },
    };

    return yaml.stringify(manifest);
  }

  /**
   * Generate Cloudflare Worker configuration
   */
  private async generateCloudflare(
    options: IaCGenerationOptions
  ): Promise<Record<string, string>> {
    const config = options.config;
    const files: Record<string, string> = {};

    // Generate wrangler.toml
    files['wrangler.toml'] = this.generateWranglerConfig(config);

    // Generate worker script
    files['worker.js'] = this.generateWorkerScript(config);

    // Generate deployment manifest
    files['deployment.yaml'] = this.generateCloudflareDeploymentManifest(config);

    return files;
  }

  /**
   * Generate wrangler.toml configuration
   */
  private generateWranglerConfig(config: IaCConfig): string {
    const appName = config.variables?.appName || 'worker';
    const lines: string[] = [];

    lines.push('name = "' + appName + '"');
    lines.push('main = "worker.js"');
    lines.push('compatibility_date = "2024-01-01"');
    lines.push('');

    // Account ID
    if (config.variables?.accountId) {
      lines.push('account_id = "' + config.variables.accountId + '"');
      lines.push('');
    }

    // Workers AI binding
    if (config.variables?.enableAI) {
      lines.push('[ai]');
      lines.push('binding = "AI"');
      lines.push('');
    }

    // KV Namespaces
    if (config.variables?.kvNamespaces) {
      for (const ns of config.variables.kvNamespaces as string[]) {
        lines.push('[[kv_namespaces]]');
        lines.push('binding = "' + ns.toUpperCase() + '"');
        lines.push('id = "' + ns + '"');
        lines.push('');
      }
    }

    // Durable Objects
    if (config.variables?.durableObjects) {
      for (const obj of config.variables.durableObjects as any[]) {
        lines.push('[[durable_objects.bindings]]');
        lines.push('name = "' + obj.name + '"');
        lines.push('class_name = "' + obj.className + '"');
        lines.push('');
      }
    }

    // R2 Buckets
    if (config.variables?.r2Buckets) {
      for (const bucket of config.variables.r2Buckets as string[]) {
        lines.push('[[r2_buckets]]');
        lines.push('binding = "' + bucket.toUpperCase() + '"');
        lines.push('bucket_name = "' + bucket + '"');
        lines.push('');
      }
    }

    // Environment variables
    if (config.variables?.env) {
      lines.push('[vars]');
      for (const [key, value] of Object.entries(config.variables.env)) {
        lines.push(key + ' = "' + value + '"');
      }
      lines.push('');
    }

    // Triggers
    if (config.variables?.triggers) {
      lines.push('[triggers]');
      lines.push('crons = ' + JSON.stringify(config.variables.triggers));
    }

    return lines.join('\n');
  }

  /**
   * Generate Worker script
   */
  private generateWorkerScript(config: IaCConfig): string {
    return `
/**
 * Cloudflare Worker generated by ClaudeFlare
 * Generated at: ${new Date().toISOString()}
 */

export default {
  async fetch(request, env, ctx) {
    // Handle incoming requests
    const url = new URL(request.url);

    // Health check endpoint
    if (url.pathname === '/health') {
      return new Response(JSON.stringify({ status: 'healthy' }), {
        headers: { 'Content-Type': 'application/json' },
      });
    }

    // Default response
    return new Response('Hello from ClaudeFlare Worker!', {
      headers: { 'Content-Type': 'text/plain' },
    });
  },

  // Scheduled event handler
  async scheduled(event, env, ctx) {
    console.log('Scheduled event:', event.cron);
  },
};
`.trim();
  }

  /**
   * Generate Cloudflare deployment manifest
   */
  private generateCloudflareDeploymentManifest(config: IaCConfig): string {
    const appName = config.variables?.appName || 'worker';

    const manifest: KubernetesManifest = {
      apiVersion: 'claudeflare.io/v1',
      kind: 'CloudflareWorker',
      metadata: {
        name: appName,
        namespace: config.variables?.namespace || 'default',
        labels: {
          app: appName,
          'managed-by': 'claudeflare',
        },
      },
      spec: {
        name: appName,
        script: 'worker.js',
        bindings: config.variables?.bindings,
        routes: config.variables?.routes,
        cronTriggers: config.variables?.triggers,
        environment: config.variables?.env,
      },
    };

    return yaml.stringify(manifest);
  }

  /**
   * Generate Helm chart
   */
  private async generateHelm(
    options: IaCGenerationOptions
  ): Promise<Record<string, string>> {
    const config = options.config;
    const files: Record<string, string> = {};

    // Chart.yaml
    files['Chart.yaml'] = this.generateHelmChartYaml(config);

    // values.yaml
    files['values.yaml'] = this.generateHelmValues(config);

    // Templates directory
    files['templates/deployment.yaml'] = this.generateHelmDeployment(config);
    files['templates/service.yaml'] = this.generateHelmService(config);
    files['templates/ingress.yaml'] = this.generateHelmIngress(config);
    files['templates/configmap.yaml'] = this.generateHelmConfigMap(config);
    files['templates/hpa.yaml'] = this.generateHelmHPA(config);
    files['templates/_helpers.tpl'] = this.generateHelmHelpers(config);

    return files;
  }

  /**
   * Generate Chart.yaml
   */
  private generateHelmChartYaml(config: IaCConfig): string {
    const appName = config.variables?.appName || 'app';

    const chart = {
      apiVersion: 'v2',
      name: appName,
      description: `Helm chart for ${appName} generated by ClaudeFlare`,
      type: 'application',
      version: config.variables?.chartVersion || '0.1.0',
      appVersion: config.variables?.appVersion || '1.0.0',
      keywords: ['claudeflare', 'deployment'],
      maintainers: [
        {
          name: 'ClaudeFlare',
          email: 'devops@claudeflare.io',
        },
      ],
    };

    return yaml.stringify(chart);
  }

  /**
   * Generate values.yaml
   */
  private generateHelmValues(config: IaCConfig): string {
    const values = {
      global: {
        environment: config.variables?.environment || 'production',
        domain: config.variables?.domain || 'example.com',
      },
      replicaCount: config.variables?.replicas || 3,
      image: {
        repository: config.variables?.imageRepository || 'nginx',
        pullPolicy: 'IfNotPresent',
        tag: config.variables?.imageTag || 'latest',
      },
      service: {
        type: config.variables?.serviceType || 'ClusterIP',
        port: config.variables?.servicePort || 80,
        targetPort: config.variables?.containerPort || 8080,
      },
      ingress: {
        enabled: config.variables?.ingressEnabled || false,
        className: 'nginx',
        annotations: {},
        hosts: [
          {
            host: config.variables?.ingressHost || 'app.example.com',
            paths: [
              {
                path: '/',
                pathType: 'Prefix',
              },
            ],
          },
        ],
        tls: [],
      },
      resources: config.variables?.resources || {
        limits: {
          cpu: '500m',
          memory: '512Mi',
        },
        requests: {
          cpu: '100m',
          memory: '128Mi',
        },
      },
      autoscaling: {
        enabled: config.variables?.enableHpa || false,
        minReplicas: 2,
        maxReplicas: 10,
        targetCPUUtilizationPercentage: 80,
        targetMemoryUtilizationPercentage: 80,
      },
    };

    return yaml.stringify(values);
  }

  /**
   * Generate Helm deployment template
   */
  private generateHelmDeployment(config: IaCConfig): string {
    return `apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        env:
        - name: ENVIRONMENT
          value: {{ .Values.global.environment }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
`;
  }

  /**
   * Generate Helm service template
   */
  private generateHelmService(config: IaCConfig): string {
    return `apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
`;
  }

  /**
   * Generate Helm ingress template
   */
  private generateHelmIngress(config: IaCConfig): string {
    return `{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if .pathType }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              service:
                name: {{ include "app.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
`;
  }

  /**
   * Generate Helm ConfigMap template
   */
  private generateHelmConfigMap(config: IaCConfig): string {
    return `apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-config
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
`;
  }

  /**
   * Generate Helm HPA template
   */
  private generateHelmHPA(config: IaCConfig): string {
    return `{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "app.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
`;
  }

  /**
   * Generate Helm helpers template
   */
  private generateHelmHelpers(config: IaCConfig): string {
    return `{{/*
Expand the name of the chart.
*/}}
{{- define "app.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
*/}}
{{- define "app.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "app.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "app.labels" -}}
helm.sh/chart: {{ include "app.chart" . }}
{{ include "app.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Selector labels
*/}}
{{- define "app.selectorLabels" -}}
app.kubernetes.io/name: {{ include "app.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
`;
  }

  /**
   * Write output to files
   */
  private async writeOutput(
    files: Record<string, string>,
    outputPath: string
  ): Promise<void> {
    for (const [filename, content] of Object.entries(files)) {
      const filePath = `${outputPath}/${filename}`;
      const directory = filePath.substring(0, filePath.lastIndexOf('/'));

      await fs.mkdir(directory, { recursive: true });
      await fs.writeFile(filePath, content, 'utf-8');
    }
  }

  /**
   * Validate configuration
   */
  private async validateConfig(config: IaCConfig): Promise<void> {
    const errors = await this.validator.validateIaCConfig(config);

    if (errors.length > 0) {
      throw new Error(`Configuration validation failed: ${errors.join(', ')}`);
    }
  }

  /**
   * Format value for Terraform
   */
  private formatTerraformValue(value: any): string {
    if (typeof value === 'string') {
      return `"${value}"`;
    } else if (typeof value === 'number') {
      return value.toString();
    } else if (typeof value === 'boolean') {
      return value.toString();
    } else if (Array.isArray(value)) {
      return `[${value.map((v) => this.formatTerraformValue(v)).join(', ')}]`;
    } else if (typeof value === 'object') {
      const pairs = Object.entries(value).map(
        ([k, v]) => `${k} = ${this.formatTerraformValue(v)}`
      );
      return `{\n    ${pairs.join('\n    ')}\n  }`;
    }
    return 'null';
  }

  /**
   * Infer Terraform type from value
   */
  private inferTerraformType(value: any): string {
    if (typeof value === 'string') return 'string';
    if (typeof value === 'number') return 'number';
    if (typeof value === 'boolean') return 'bool';
    if (Array.isArray(value)) return 'list(any)';
    if (typeof value === 'object') return 'map(any)';
    return 'any';
  }
}
