/**
 * Basic Usage Examples for LLM Orchestration
 */

import {
  createOrchestrationEngine,
  LLMOrchestrationEngine,
} from '../src/index';
import type {
  LLMRequest,
  BudgetConfig,
  RateLimitQuota,
} from '../src/types/index';

// ============================================================================
// Example 1: Basic Request Execution
// ============================================================================

async function basicRequestExample() {
  const engine = createOrchestrationEngine();

  // Register a provider (in real usage, you'd use actual provider clients)
  engine.registerProvider('openai', {
    async chat(request: LLMRequest) {
      // Actual API call would go here
      return {
        id: 'resp-1',
        model: request.model || 'gpt-4',
        choices: [
          {
            index: 0,
            message: {
              role: 'assistant',
              content: 'Hello! How can I help you today?',
            },
            finishReason: 'stop',
          },
        ],
        usage: {
          promptTokens: 10,
          completionTokens: 9,
          totalTokens: 19,
        },
        created: Date.now(),
      };
    },
  });

  // Execute a simple request
  const request: LLMRequest = {
    messages: [
      { role: 'user', content: 'Hello, how are you?' },
    ],
  };

  const response = await engine.execute(request);
  console.log('Response:', response.choices[0].message.content);

  engine.dispose();
}

// ============================================================================
// Example 2: Intelligent Routing
// ============================================================================

async function routingExample() {
  const engine = createOrchestrationEngine({
    enableRouting: true,
  });

  // Code generation request - routes to best code model
  const codeRequest: LLMRequest = {
    messages: [
      {
        role: 'user',
        content: 'Write a function to validate email addresses in JavaScript',
      },
    ],
  };

  const codeResponse = await engine.execute(codeRequest, {
    routing: {
      strategy: 'capability',
      capabilityRequirements: {
        codeGeneration: { supported: true, confidence: 0.9 },
      },
    },
  });

  console.log('Code generated by model:', codeResponse.model);

  // Cost-optimized request
  const simpleRequest: LLMRequest = {
    messages: [
      { role: 'user', content: 'What is 2 + 2?' },
    ],
  };

  const costOptimizedResponse = await engine.execute(simpleRequest, {
    routing: {
      strategy: 'cost',
      costLimit: 5,
    },
  });

  console.log('Cost-optimized response from:', costOptimizedResponse.model);

  engine.dispose();
}

// ============================================================================
// Example 3: Budget Management
// ============================================================================

async function budgetExample() {
  const engine = createOrchestrationEngine({
    enableCostTracking: true,
  });

  // Create a budget
  const dailyBudget: BudgetConfig = {
    id: 'daily-budget',
    name: 'Daily API Budget',
    limit: 10, // $10 per day
    period: 'daily',
    scope: 'global',
    alertThreshold: 0.8, // Alert at 80%
    actions: [
      {
        type: 'alert',
        threshold: 0.8,
      },
      {
        type: 'throttle',
        threshold: 0.9,
      },
    ],
  };

  engine.createBudget(dailyBudget);

  // Execute requests with budget tracking
  for (let i = 0; i < 10; i++) {
    try {
      const request: LLMRequest = {
        messages: [
          { role: 'user', content: `Question ${i}` },
        ],
      };

      await engine.execute(request, {
        userId: 'user-123',
      });
    } catch (error: any) {
      if (error.code === 'BUDGET_EXCEEDED') {
        console.log('Budget exceeded, stopping requests');
        break;
      }
    }
  }

  // Check budget spending
  const costOptimizer = (engine as any).costOptimizer;
  const spending = costOptimizer.getBudgetSpending('daily-budget');
  console.log('Total spending:', spending);

  engine.dispose();
}

// ============================================================================
// Example 4: Rate Limiting
// ============================================================================

async function rateLimitExample() {
  const engine = createOrchestrationEngine({
    enableRateLimiting: true,
  });

  // Create rate limit quota
  const userQuota: RateLimitQuota = {
    id: 'free-tier-quota',
    name: 'Free Tier Quota',
    scope: 'user',
    scopeId: 'user-123',
    limits: {
      requests: 100,
      tokens: 50000,
      window: 3600000, // 1 hour
    },
    priority: 1,
  };

  engine.createRateLimit(userQuota);

  // Execute requests with rate limiting
  for (let i = 0; i < 150; i++) {
    try {
      const request: LLMRequest = {
        messages: [
          { role: 'user', content: `Request ${i}` },
        ],
      };

      await engine.execute(request, {
        userId: 'user-123',
      });

      console.log(`Request ${i} succeeded`);
    } catch (error: any) {
      if (error.code === 'RATE_LIMIT_EXCEEDED') {
        console.log(`Rate limit exceeded at request ${i}`);
        console.log('Resets at:', new Date(error.details.resetTime));
        break;
      }
    }
  }

  engine.dispose();
}

// ============================================================================
// Example 5: Multi-Model Aggregation
// ============================================================================

async function aggregationExample() {
  const engine = createOrchestrationEngine({
    enableAggregation: true,
  });

  // Complex question requiring multiple perspectives
  const request: LLMRequest = {
    messages: [
      {
        role: 'user',
        content: 'What are the pros and cons of microservices architecture?',
      },
    ],
  };

  // Aggregate responses from multiple models
  const response = await engine.execute(request, {
    multiModel: true,
    aggregation: {
      method: 'consensus',
      strategy: 'majority',
      threshold: 0.7,
    },
  });

  console.log('Aggregated response:', response.choices[0].message.content);
  console.log('Consensus level:', (response.metadata as any).aggregated.consensus);

  engine.dispose();
}

// ============================================================================
// Example 6: Prompt Templates
// ============================================================================

async function promptTemplateExample() {
  const engine = createOrchestrationEngine({
    enablePromptEngine: true,
  });

  const promptEngine = (engine as any).promptEngine;

  // Render a prompt template
  const templateId = 'question-answering';
  const variables = {
    context: 'Python is a high-level programming language...',
    question: 'What is Python?',
    constraints: 'Keep the answer under 100 words',
  };

  const renderedPrompt = promptEngine.render(templateId, variables);
  console.log('Rendered prompt:', renderedPrompt);

  // Use the rendered prompt
  const request: LLMRequest = {
    messages: [
      { role: 'user', content: renderedPrompt },
    ],
  };

  await engine.execute(request);

  // Optimize the template
  const optimizationResult = await promptEngine.optimize(templateId);
  console.log('Optimization suggestions:', optimizationResult.suggestions);

  engine.dispose();
}

// ============================================================================
// Example 7: Analytics and Monitoring
// ============================================================================

async function analyticsExample() {
  const engine = createOrchestrationEngine();

  // Execute some requests
  for (let i = 0; i < 20; i++) {
    const request: LLMRequest = {
      messages: [
        { role: 'user', content: `Test request ${i}` },
      ],
    };

    await engine.execute(request);
  }

  // Get comprehensive analytics
  const analytics = engine.getAnalytics();

  console.log('Model Analytics:', {
    totalModels: analytics.registry.totalModels,
    availableModels: analytics.registry.availableModels,
  });

  console.log('Routing Analytics:', {
    totalRequests: analytics.router.totalRequests,
    modelUsage: analytics.router.modelUsage,
  });

  console.log('Cost Analytics:', {
    totalTracked: analytics.cost.totalTracked,
    totalSpending: analytics.cost.totalSpending,
  });

  console.log('Rate Limit Analytics:', {
    totalQuotas: analytics.rateLimit.totalQuotas,
    activeStates: analytics.rateLimit.activeStates,
  });

  engine.dispose();
}

// ============================================================================
// Example 8: Event Handling
// ============================================================================

async function eventHandlingExample() {
  const engine = createOrchestrationEngine();

  // Listen to events
  engine.on('request:start', (data: any) => {
    console.log('Request started:', data.requestId);
  });

  engine.on('routing:decision', (data: any) => {
    console.log('Routing decision:', data.decision.model);
  });

  engine.on('request:complete', (data: any) => {
    console.log('Request completed in', data.duration, 'ms');
  });

  engine.on('budget:exceeded', (data: any) => {
    console.log('Budget exceeded:', data.budget);
  });

  engine.on('rate-limit:exceeded', (data: any) => {
    console.log('Rate limit exceeded:', data.scope);
  });

  // Execute a request
  const request: LLMRequest = {
    messages: [
      { role: 'user', content: 'Hello' },
    ],
  };

  await engine.execute(request);

  engine.dispose();
}

// ============================================================================
// Example 9: Error Handling
// ============================================================================

async function errorHandlingExample() {
  const engine = createOrchestrationEngine({
    enableFallback: true,
    maxRetries: 3,
  });

  // Handle different error types
  try {
    const request: LLMRequest = {
      messages: [
        { role: 'user', content: 'Help me write code' },
      ],
    };

    const response = await engine.execute(request, {
      routing: {
        fallbackEnabled: true,
        fallbackModels: ['gpt-3.5-turbo', 'claude-3-haiku'],
      },
    });

    console.log('Response:', response.choices[0].message.content);
  } catch (error: any) {
    switch (error.code) {
      case 'MODEL_UNAVAILABLE':
        console.log('Model unavailable, try again later');
        break;
      case 'RATE_LIMIT_EXCEEDED':
        console.log('Rate limited, retry after:', error.details.resetTime);
        break;
      case 'BUDGET_EXCEEDED':
        console.log('Budget exceeded, limit:', error.details.limit);
        break;
      default:
        console.log('Unexpected error:', error.message);
    }
  }

  engine.dispose();
}

// ============================================================================
// Example 10: Advanced Configuration
// ============================================================================

async function advancedConfigExample() {
  const engine = createOrchestrationEngine({
    enableRouting: true,
    enableAggregation: true,
    enablePromptEngine: true,
    enableCostTracking: true,
    enableRateLimiting: true,
    enableCaching: true,
    defaultRoutingStrategy: 'weighted',
    defaultAggregationMethod: 'consensus',
    cacheTTL: 3600000, // 1 hour
    maxRetries: 3,
    timeout: 30000, // 30 seconds
  });

  // Create budgets
  const dailyBudget: BudgetConfig = {
    id: 'daily',
    name: 'Daily Budget',
    limit: 50,
    period: 'daily',
    scope: 'global',
    hardLimit: false,
  };

  const userBudget: BudgetConfig = {
    id: 'user-123',
    name: 'User 123 Budget',
    limit: 10,
    period: 'daily',
    scope: 'user',
    scopeId: 'user-123',
    hardLimit: true,
  };

  engine.createBudget(dailyBudget);
  engine.createBudget(userBudget);

  // Create rate limits
  const globalQuota: RateLimitQuota = {
    id: 'global',
    name: 'Global Rate Limit',
    scope: 'global',
    limits: {
      requests: 1000,
      tokens: 1000000,
      window: 3600000,
    },
  };

  const userQuota: RateLimitQuota = {
    id: 'user-123',
    name: 'User Rate Limit',
    scope: 'user',
    scopeId: 'user-123',
    limits: {
      requests: 100,
      tokens: 100000,
      window: 3600000,
    },
  };

  engine.createRateLimit(globalQuota);
  engine.createRateLimit(userQuota);

  // Execute with full options
  const request: LLMRequest = {
    messages: [
      { role: 'user', content: 'Complex analysis request' },
    ],
  };

  const response = await engine.execute(request, {
    userId: 'user-123',
    priority: 5,
    multiModel: true,
    routing: {
      strategy: 'performance',
      fallbackEnabled: true,
    },
    aggregation: {
      method: 'weighted',
      strategy: 'best',
    },
  });

  console.log('Advanced execution complete');

  engine.dispose();
}

// ============================================================================
// Run Examples
// ============================================================================

export async function runExamples() {
  console.log('=== Basic Request Example ===');
  await basicRequestExample();

  console.log('\n=== Routing Example ===');
  await routingExample();

  console.log('\n=== Budget Example ===');
  await budgetExample();

  console.log('\n=== Rate Limit Example ===');
  await rateLimitExample();

  console.log('\n=== Aggregation Example ===');
  await aggregationExample();

  console.log('\n=== Prompt Template Example ===');
  await promptTemplateExample();

  console.log('\n=== Analytics Example ===');
  await analyticsExample();

  console.log('\n=== Event Handling Example ===');
  await eventHandlingExample();

  console.log('\n=== Error Handling Example ===');
  await errorHandlingExample();

  console.log('\n=== Advanced Config Example ===');
  await advancedConfigExample();
}
